# Generated by Django 5.2.18 on 2026-10-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_developer',
            field=models.BooleanField(default=True, verbose_name='是否是有权限的开发者'),
        ),
    ]
