# Generated by Django 5.2.18 on 2026-10-07 10:55

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_user_is_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid6, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_key', models.CharField(max_length=512, unique=True, verbose_name='对象键')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('content_type', models.CharField(blank=True, max_length=255, verbose_name='内容类型')),
                ('size', models.BigIntegerField(verbose_name='文件大小')),
                ('uploader_id', models.UUIDField(verbose_name='上传者 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
                'db_table': 'files',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
